---
title: "Untitled"
author: "cathy"
date: "2024-11-07"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

do some boostrapping

```{r}
n_samp = 250

sim_df_constant = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_constant |> 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

let's look at these.

```{r}
sim_df_nonconst |> 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  stat_smooth(method = "lm")
```

look at regerssion results
```{r}
sim_df_constant |> 
  lm(y ~ x, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

## draw a bootstrap sample

```{r}
boot_sample = function(df){
  
  boot_df = 
    sample_frac(df, replace = TRUE) |> 
    arrange(x)
  
  return(boot_df)
  
  }
```

let's try running this!
```{r}
sim_df_constant |> 
  boot_sample() |> 
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```

can we do this as part of an analysis?
```{r}
sim_df_constant |> 
  boot_sample() |> 
  lm(y ~ x, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```





